In [11]:
import numpy as np
import time

# Генерация двух матриц с дробными значениями
matrix1 = np.random.rand(10000, 10000)
matrix2 = np.random.rand(10000, 10000)

# Измерение времени умножения двух матриц с дробными значениями
start_time = time.time()
result1 = np.dot(matrix1, matrix2)
end_time = time.time()
execution_time1 = end_time - start_time
print("Время умножения двух матриц с дробными значениями:", execution_time1, "сек")

# Генерация двух матриц с значениями 0 или 1
matrix3 = np.random.randint(2, size=(10000, 10000), dtype = np.int16)
matrix4 = np.random.randint(2, size=(10000, 10000), dtype = np.int16)

# Измерение времени умножения двух матриц с значениями 0 или 1
start_time = time.time()
result2 = np.dot(matrix3, matrix4)
end_time = time.time()
execution_time2 = end_time - start_time
print("Время умножения двух матриц с значениями 0 или 1:", execution_time2, "сек")


Время умножения двух матриц с дробными значениями: 41.5551073551178 сек
Время умножения двух матриц с значениями 0 или 1: 4891.83182311058 сек


In [12]:
# Генерация двух матриц с значениями 0 или 1
matrix5 = matrix3.astype(bool)
matrix6 = matrix4.astype(bool)

# Измерение времени умножения двух матриц с значениями 0 или 1
start_time = time.time()
result2 = np.dot(matrix5, matrix6)
end_time = time.time()
execution_time2 = end_time - start_time
print("Время умножения двух матриц с значениями 0 или 1:", execution_time2, "сек")


Время умножения двух матриц с значениями 0 или 1: 1.522479772567749 сек


In [9]:
matrix3.nbytes

2000000

In [3]:
import numpy as np

# Создание массива целых чисел
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Проверка размера памяти, занимаемого массивом
print("Размер памяти до изменения:", arr.nbytes, "байт")

# Преобразование массива в int16
arr = arr.astype(np.int16)

# Проверка размера памяти после изменения
print("Размер памяти после изменения:", arr.nbytes, "байт")


Размер памяти до изменения: 20 байт
Размер памяти после изменения: 10 байт


In [1]:
import numpy as np
import time

In [66]:
a = np.random.randint(10, size=(10, 2), dtype = np.int16)
a = a.astype(bool)

In [67]:
a

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False],
       [ True,  True],
       [ True, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [68]:
type(a)

numpy.ndarray

In [69]:
c = np.array([[False,False,True,False], [False,True,False,False]])

In [70]:
a, c

(array([[ True,  True],
        [ True,  True],
        [ True,  True],
        [False, False],
        [ True,  True],
        [ True, False],
        [False,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]]),
 array([[False, False,  True, False],
        [False,  True, False, False]]))

In [71]:
a = a[:,:,np.newaxis]
a.shape

(10, 2, 1)

In [72]:
a.shape, c.shape

((10, 2, 1), (2, 4))

In [73]:
a, c

(array([[[ True],
         [ True]],
 
        [[ True],
         [ True]],
 
        [[ True],
         [ True]],
 
        [[False],
         [False]],
 
        [[ True],
         [ True]],
 
        [[ True],
         [False]],
 
        [[False],
         [ True]],
 
        [[ True],
         [ True]],
 
        [[ True],
         [ True]],
 
        [[ True],
         [ True]]]),
 array([[False, False,  True, False],
        [False,  True, False, False]]))

In [74]:
m = np.einsum('ij, kim-> kij', c, a) # (2,4) (10,2,1)
m

array([[[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False, False, False],
        [False, False, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]]])

In [75]:
m.shape

(10, 2, 4)

0

In [76]:
import numpy as np

# Исходная матрица размерности (n, i, j)
matrix = np.array([[[0, 1, 0, 0, 1, 1],
                   [0, 1, 1, 1, 0, 0],
                   [1, 1, 0, 1, 0, 1]],

                  [[1, 1, 1, 0, 1, 1],
                   [0, 0, 1, 0, 1, 0],
                   [1, 0, 0, 1, 1, 0]]])

# Получение матрицы сумм по размерности j
sum_matrix = np.sum(matrix, axis=1)

# Преобразование матрицы сумм в кумулятивные суммы по каждому из n векторов
cumulative_sum_matrix = np.cumsum(sum_matrix, axis=0)

# Вывод результирующей матрицы
print(cumulative_sum_matrix)


[[1 3 1 2 1 2]
 [3 4 3 3 4 3]]


In [77]:
a = np.array([0,1,1,0,0,1])

In [78]:
np.cumsum(a)

array([0, 1, 2, 2, 2, 3])

In [79]:
matrix = np.array([[[0, 1, 0, 0, 1, 1],
                   [0, 1, 1, 1, 0, 0],
                   [1, 1, 0, 1, 0, 1]],

                  [[1, 1, 1, 0, 1, 1],
                   [0, 0, 1, 0, 1, 0],
                   [1, 0, 0, 1, 1, 0]]])



In [86]:
c = np.sum(matrix, axis = 1)
c

array([[1, 3, 1, 2, 1, 2],
       [2, 1, 2, 1, 3, 1]])

In [87]:
d = np.cumsum(c, axis = 1)
d

array([[ 1,  4,  5,  7,  8, 10],
       [ 2,  3,  5,  6,  9, 10]])

In [82]:
d

array([0, 0, 1, 1, 1, 2, 2, 2])