In [11]:
import numpy as np
import time

# Генерация двух матриц с дробными значениями
matrix1 = np.random.rand(10000, 10000)
matrix2 = np.random.rand(10000, 10000)

# Измерение времени умножения двух матриц с дробными значениями
start_time = time.time()
result1 = np.dot(matrix1, matrix2)
end_time = time.time()
execution_time1 = end_time - start_time
print("Время умножения двух матриц с дробными значениями:", execution_time1, "сек")

# Генерация двух матриц с значениями 0 или 1
matrix3 = np.random.randint(2, size=(10000, 10000), dtype = np.int16)
matrix4 = np.random.randint(2, size=(10000, 10000), dtype = np.int16)

# Измерение времени умножения двух матриц с значениями 0 или 1
start_time = time.time()
result2 = np.dot(matrix3, matrix4)
end_time = time.time()
execution_time2 = end_time - start_time
print("Время умножения двух матриц с значениями 0 или 1:", execution_time2, "сек")


Время умножения двух матриц с дробными значениями: 41.5551073551178 сек
Время умножения двух матриц с значениями 0 или 1: 4891.83182311058 сек


In [12]:
# Генерация двух матриц с значениями 0 или 1
matrix5 = matrix3.astype(bool)
matrix6 = matrix4.astype(bool)

# Измерение времени умножения двух матриц с значениями 0 или 1
start_time = time.time()
result2 = np.dot(matrix5, matrix6)
end_time = time.time()
execution_time2 = end_time - start_time
print("Время умножения двух матриц с значениями 0 или 1:", execution_time2, "сек")


Время умножения двух матриц с значениями 0 или 1: 1.522479772567749 сек


In [9]:
matrix3.nbytes

2000000

In [3]:
import numpy as np

# Создание массива целых чисел
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Проверка размера памяти, занимаемого массивом
print("Размер памяти до изменения:", arr.nbytes, "байт")

# Преобразование массива в int16
arr = arr.astype(np.int16)

# Проверка размера памяти после изменения
print("Размер памяти после изменения:", arr.nbytes, "байт")


Размер памяти до изменения: 20 байт
Размер памяти после изменения: 10 байт


In [1]:
import numpy as np
import time

In [66]:
a = np.random.randint(10, size=(10, 2), dtype = np.int16)
a = a.astype(bool)

In [67]:
a

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False],
       [ True,  True],
       [ True, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [68]:
type(a)

numpy.ndarray

In [69]:
c = np.array([[False,False,True,False], [False,True,False,False]])

In [70]:
a, c

(array([[ True,  True],
        [ True,  True],
        [ True,  True],
        [False, False],
        [ True,  True],
        [ True, False],
        [False,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]]),
 array([[False, False,  True, False],
        [False,  True, False, False]]))

In [71]:
a = a[:,:,np.newaxis]
a.shape

(10, 2, 1)

In [72]:
a.shape, c.shape

((10, 2, 1), (2, 4))

In [73]:
a, c

(array([[[ True],
         [ True]],
 
        [[ True],
         [ True]],
 
        [[ True],
         [ True]],
 
        [[False],
         [False]],
 
        [[ True],
         [ True]],
 
        [[ True],
         [False]],
 
        [[False],
         [ True]],
 
        [[ True],
         [ True]],
 
        [[ True],
         [ True]],
 
        [[ True],
         [ True]]]),
 array([[False, False,  True, False],
        [False,  True, False, False]]))

In [74]:
m = np.einsum('ij, kim-> kij', c, a) # (2,4) (10,2,1)
m

array([[[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False, False, False],
        [False, False, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]],

       [[False, False,  True, False],
        [False,  True, False, False]]])

In [75]:
m.shape

(10, 2, 4)

0

In [76]:
import numpy as np

# Исходная матрица размерности (n, i, j)
matrix = np.array([[[0, 1, 0, 0, 1, 1],
                   [0, 1, 1, 1, 0, 0],
                   [1, 1, 0, 1, 0, 1]],

                  [[1, 1, 1, 0, 1, 1],
                   [0, 0, 1, 0, 1, 0],
                   [1, 0, 0, 1, 1, 0]]])

# Получение матрицы сумм по размерности j
sum_matrix = np.sum(matrix, axis=1)

# Преобразование матрицы сумм в кумулятивные суммы по каждому из n векторов
cumulative_sum_matrix = np.cumsum(sum_matrix, axis=0)

# Вывод результирующей матрицы
print(cumulative_sum_matrix)


[[1 3 1 2 1 2]
 [3 4 3 3 4 3]]


In [77]:
a = np.array([0,1,1,0,0,1])

In [78]:
np.cumsum(a)

array([0, 1, 2, 2, 2, 3])

In [79]:
matrix = np.array([[[0, 1, 0, 0, 1, 1],
                   [0, 1, 1, 1, 0, 0],
                   [1, 1, 0, 1, 0, 1]],

                  [[1, 1, 1, 0, 1, 1],
                   [0, 0, 1, 0, 1, 0],
                   [1, 0, 0, 1, 1, 0]]])



In [86]:
c = np.sum(matrix, axis = 1)
c

array([[1, 3, 1, 2, 1, 2],
       [2, 1, 2, 1, 3, 1]])

In [87]:
d = np.cumsum(c, axis = 1)
d

array([[ 1,  4,  5,  7,  8, 10],
       [ 2,  3,  5,  6,  9, 10]])

In [82]:
d

array([0, 0, 1, 1, 1, 2, 2, 2])

In [102]:
import numpy as np

# Исходная матрица размерности (10, 5)
matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25],
                   [26, 27, 28, 29, 30],
                   [31, 32, 33, 34, 35],
                   [36, 37, 38, 39, 40],
                   [41, 42, 43, 44, 45],
                   [46, 47, 48, 49, 50]])

# Пороговое значение
threshold = 23

# Создание маски, отмечающей значения больше порогового
mask = matrix > threshold

# Определение позиции первого True значения в маске
position = np.argmax(mask, axis=1)

# Определение строк, в которых встречается значение раньше
earliest_rows = np.where(position == np.min(position))[0]

# Вывод результата
print("Первое значение > порогового встречается на позиции:")
print(position)
print("Строки, в которых встречается раньше:")
print(earliest_rows)


Первое значение > порогового встречается на позиции:
[0 0 0 0 3 0 0 0 0 0]
Строки, в которых встречается раньше:
[0 1 2 3 5 6 7 8 9]


In [93]:
matrix>threshold

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [92]:
np.where(matrix>threshold)

(array([5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9,
        9, 9, 9], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
        2, 3, 4], dtype=int64))

In [101]:
np.argmax(mask, axis=0)

array([5, 5, 5, 5, 5], dtype=int64)

In [94]:
d = np.array([0,1,2,3,4,5,6,7,8,9])

In [95]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
d[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [97]:
matrix>d

ValueError: operands could not be broadcast together with shapes (10,5) (10,) 

In [103]:
import numpy as np

# Исходная матрица размерности (10, 5)
matrix = np.array([[1, 2, 3, 4, 5],
                   [2, 4, 6, 8, 10],
                   [3, 6, 9, 12, 15],
                   [4, 8, 12, 16, 20],
                   [5, 10, 15, 20, 25],
                   [6, 12, 18, 24, 30],
                   [7, 14, 21, 28, 35],
                   [8, 16, 24, 32, 40],
                   [9, 18, 27, 36, 45],
                   [10, 20, 30, 40, 50]])

# Пороговые значения для каждой строки
thresholds = [3, 20, 9, 40, 50, 60, 70, 80, 90, 100]

m = matrix.apply(, axis = 1)

# Определение позиции первого значения, превышающего порог, в каждой строке
first_exceed_positions = np.argmax(matrix > np.array(thresholds)[:, np.newaxis], axis=1)

# Определение строк, в которых значение превышающее порог появляется раньше
earliest_rows = np.where(first_exceed_positions == np.min(first_exceed_positions))[0]

# Вывод результатов
print("Первое превышение порога появляется на позиции:")
for row in earliest_rows:
    print(f"Строка {row + 1}: Позиция {first_exceed_positions[row]}")


Первое превышение порога появляется на позиции:
Строка 2: Позиция 0
Строка 4: Позиция 0
Строка 5: Позиция 0
Строка 6: Позиция 0
Строка 7: Позиция 0
Строка 8: Позиция 0
Строка 9: Позиция 0
Строка 10: Позиция 0


In [100]:
b = np.array([False, False, True, False, True])
np.argmax(b)

2

In [105]:
matrix  = np.random.randint(20, size = (10, 4), dtype = np.int16)

In [106]:
matrix

array([[ 3, 17, 13, 12],
       [ 5,  6, 17,  9],
       [12,  9, 14, 17],
       [18, 12, 14, 11],
       [19,  6,  7, 18],
       [18,  5,  3,  0],
       [19, 17, 13, 13],
       [ 2, 16,  5,  7],
       [ 2,  3,  2, 17],
       [14, 12, 11,  6]], dtype=int16)

In [111]:
thresholds = np.random.randint(low = 10, high=20, size = (10,1), dtype = np.int16)


In [112]:
thresholds

array([[13],
       [11],
       [13],
       [17],
       [11],
       [14],
       [12],
       [11],
       [10],
       [13]], dtype=int16)

In [116]:
thresholds[9] = 25

In [117]:
comp = matrix>thresholds

In [118]:
comp

array([[False,  True, False, False],
       [False, False,  True, False],
       [False, False,  True,  True],
       [ True, False, False, False],
       [ True, False, False,  True],
       [ True, False, False, False],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [119]:
np.argmax(comp, axis = 1)

array([1, 2, 2, 0, 0, 0, 0, 1, 3, 0], dtype=int64)

In [2]:
import numpy as np
import time

In [3]:
vec = np.random.randint(2, size=(7), dtype = np.int16)

In [4]:
vec

array([0, 0, 0, 0, 1, 0, 1], dtype=int16)

In [9]:
np.append(vec[-1], vec[:-1])

array([1, 0, 0, 0, 0, 1, 0], dtype=int16)

In [7]:
vec[-1]

1